### ISSUE TITLE
Create a broadcast 

### ISSUE THREAD

**Issue by coderaavan** [coderaavan/fbChatPython#10]

**Comment by CSaratakij** [comment]
I don't understand this feature. Does it like group chat?

**Comment by coderaavan** [comment]
@CSaratakij A feature like whatsapp broadcast. You can enter multiple friend names and one message will be sent to all of them not in group but as personal message.

**Comment by thakkardharmik** [comment]
@coderaavan created PR#27 for this.

**Comment by CSaratakij** [comment]
@thakkardharmik I almost finished this feature too...
(Will send my PR too xD)

**Comment by CSaratakij** [comment]
Okay, my PR #28
