### ISSUE TITLE
Couldn't log in

### ISSUE THREAD

**Issue by iamnottheway** [coderaavan/fbChatPython#40]
@CSaratakij I want to improve the UI, so I  tried logging in but it gives me an error.  So, I just improved the login form UI.

 Know whats wrong? What creds am I supposed to enter? email and password or something else?

**Comment by CSaratakij** [comment]
@HarowitzBlack I have tested. It seem doing fine (login successful)
Nice UI improvement, you might want to polish formchatbox xD

**Comment by iamnottheway** [comment]
It worked! I'll start working on the chatbox UI.
@CSaratakij  Any features in mind?

@coderaavan instead of using the parent window and terminal to show the error messages, we could implement a message box class. Any thoughts?

**Comment by CSaratakij** [comment]
@HarowitzBlack feature in mind would be like -> 
- message box that can send & recieve message, 
- show chat log history
- show friend online status
(probably do receive message first)
