### ISSUE TITLE
Create a Logout button for safe logout

### ISSUE THREAD

**Issue by coderaavan** [coderaavan/fbChatPython#7]

**Comment by thakkardharmik** [comment]
@coderaavan  I would like to give it a try. Is this still unassigned?

**Comment by coderaavan** [comment]
Yes @thakkardharmik go for it.

**Comment by CSaratakij** [comment]
I did try to add logout button here -> #18 xD

**Comment by coderaavan** [comment]
Yes @CSaratakij #18 merged.
